// Generated by tools/genmap.py -- do not edit.
//
// Natural Earth 1:110m, simplified at 0.1 degrees, baked to int16
// unit sphere vectors. Source data is public domain.
#pragma once

#include <cstdint>

namespace geoscout {

// One run of vertices in kWorldPoints.
struct GeoPolyline {
    uint16_t first;
    uint16_t count;
};

// Unit sphere vectors scaled by 32767. +Z north, +X at 0N 0E.
extern const int16_t kWorldPoints[][3];
constexpr int kWorldPointCount = 6772;

extern const GeoPolyline kCoastLines[];
constexpr int kCoastLineCount = 130;

extern const GeoPolyline kBorderLines[];
constexpr int kBorderLineCount = 308;

extern const GeoPolyline kLakeLines[];
constexpr int kLakeLineCount = 22;

}  // namespace geoscout
